namespace: epfl_si

name: python_frameworks

version: 0.1.0

readme: README.md

authors:
- ISAS-FSD <isas-fsd@groupes.epfl.ch>

description: Support for writing Ansible tasks that call ORMs (Django etc.) or other Python frameworks to get their job done

license:
- GPL-2.0-only

tags:
- django
- framework
- orm
- object_relational_mapper
- postcondition

dependencies:
  epfl_si.actions: ">=1.2.0"

repository: https://github.com/epfl-si/ansible-collection-python-frameworks

issues: https://github.com/epfl-si/ansible-collection-python-frameworks/issues
